# scripts/remediate.py
import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

# This map links a ControlId to a PowerShell command that can remediate the issue.
# The {Value} placeholder can be used for controls where the remediation depends on the 'Actual' value.
# IMPORTANT: All commands should include -WhatIf for safety.
REMEDIATION_MAP = {
    "1.1.1": "# Control 1.1.1: Ensure MFA is enabled for all administrative roles.\n# Remediation: Manually review and enable MFA for admins in the Azure AD portal.",
    "1.1.2": "Set-OrganizationConfig -OAuth2ClientProfileEnabled $true # Ensure modern authentication is enabled.",
    "2.1.5": "Set-AdminAuditLogConfig -AdminAuditLogEnabled $true # Ensure admin audit logging is enabled.",
    # Example for a control that might need a value from the report
    # "3.1.1": "Set-AuthenticationPolicy -Identity '{Value}' -AllowBasicAuth $false",
}


def generate_remediation_plan(failed_controls: List[Dict[str, Any]], output_path: Path):
    """
    Generates a PowerShell script to remediate failed controls.

    Args:
        failed_controls: A list of control objects that have failed.
        output_path: The path to write the PowerShell script to.
    """
    script_content = [
        "# M365 CIS Remediation Plan",
        "# Generated by remediate.py",
        "# Review these commands carefully before execution.",
        "# All commands are generated with -WhatIf for a safe preview.",
        "\n# Connect to required services (uncomment as needed)",
        "# Connect-ExchangeOnline",
        '# Connect-MgGraph -Scopes "Policy.ReadWrite.AuthenticationMethod, Directory.ReadWrite.All"\n',
    ]

    remediation_count = 0
    for control in failed_controls:
        control_id = control.get("ControlId")
        if control_id in REMEDIATION_MAP:
            remediation_command = REMEDIATION_MAP[control_id]

            # Handle simple placeholders if needed in the future
            # actual_value = control.get("Actual")
            # if "{Value}" in remediation_command and actual_value:
            #     remediation_command = remediation_command.format(Value=actual_value)

            script_content.append(f"# Remediation for Control: {control_id} - {control.get('Title')}")
            if remediation_command.strip().startswith("#"):
                script_content.append(remediation_command + "\n")
                # Do not increment remediation_count for comment/manual remediations
            else:
                script_content.append(remediation_command + " -WhatIf\n")
                remediation_count += 1
        else:
            script_content.append(
                f"# No automated remediation available for Control: {control_id} - {control.get('Title')}"
            )
            script_content.append("# Please review manually.\n")

    if remediation_count == 0:
        print("No automated remediation actions were generated as no failed controls had a corresponding action.")
    else:
        print(f"Generated remediation plan with {remediation_count} actions.")

    output_path.write_text("\n".join(script_content), encoding="utf-8")
    print(f"Remediation script saved to: {output_path}")


def main():
    """Main function to parse arguments and run remediation."""
    parser = argparse.ArgumentParser(description="Generate a remediation plan from an M365 CIS audit JSON report.")
    parser.add_argument(
        "report_file",
        type=str,
        help="Path to the M365 CIS audit JSON report file.",
    )
    parser.add_argument(
        "--output-file",
        type=str,
        default="remediation_plan.ps1",
        help="Path to save the generated PowerShell remediation script.",
    )
    args = parser.parse_args()

    report_path = Path(args.report_file)
    output_path = Path(args.output_file)

    if not report_path.exists():
        print(f"Error: Report file not found at {report_path}", file=sys.stderr)
        sys.exit(1)

    try:
        data = json.loads(report_path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in {report_path}: {e}", file=sys.stderr)
        sys.exit(1)

    failed_controls = [c for c in data if c.get("Status") == "Fail"]

    if not failed_controls:
        print("No failed controls found. Nothing to remediate.")
        return

    generate_remediation_plan(failed_controls, output_path)


if __name__ == "__main__":
    main()
